### ISSUE TITLE
urllib2 error

### ISSUE THREAD

**Issue by sflinter** [yacoob/aib2ofx#22]
I'm getting the following error when I run the script

```
Traceback (most recent call last):
  File "/usr/local/bin/aib2ofx", line 9, in <module>
    load_entry_point('aib2ofx==0.5.1', 'console_scripts', 'aib2ofx')()
  File "/Library/Python/2.7/site-packages/aib2ofx/main.py", line 106, in main
    chatter)
  File "/Library/Python/2.7/site-packages/aib2ofx/main.py", line 63, in getData
    show_and_tell('Logging in as \'%s\'...' % user, bank.login)
  File "/Library/Python/2.7/site-packages/aib2ofx/main.py", line 54, in show_and_tell
    function(chatter)
  File "/Library/Python/2.7/site-packages/aib2ofx/aib.py", line 128, in login
    br.open('https://onlinebanking.aib.ie/inet/roi/login.htm')
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_mechanize.py", line 203, in open
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_mechanize.py", line 230, in _mech_open
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_opener.py", line 193, in open
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_urllib2_fork.py", line 344, in _open
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_urllib2_fork.py", line 332, in _call_chain
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_urllib2_fork.py", line 1170, in https_open
  File "build/bdist.macosx-10.11-intel/egg/mechanize/_urllib2_fork.py", line 1118, in do_open
urllib2.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
```

It looks to me like a dependency-type error.

**Comment by yacoob** [comment]
First of all, apologies for the delay. That's life for you :)

I must say I can't replicate this; I've tried with a fresh install from either `master` and `next`, and things work just fine. `sslv3 alert handshake` suggests problems during SSL negotiation when fetching pages from AIB - maybe they had a moment when their frontend was failing? Or maybe you were using a proxy that malfunctioned?

Last but not least: I'll try to update aib2ofx to python3 soon-ish. It'll also include a dependency change, including getting rid of `mechanize`. If you see this as a persistent problem, maybe things will improve for you afterwards.
